// Packages
import type { Metadata } from "next"
import { Geist } from "next/font/google"
// Dictionaries
import {
  DEFAULT_LANGUAGE,
  getDictionary,
  Locale,
} from "@/dictionaries/dictionaries"
// Components
import Header from "@/components/common/Header/Header"
// Styles
import "../globals.css"

interface RootLayoutProps {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const geist = Geist({
  subsets: ["latin"],
})

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lang = DEFAULT_LANGUAGE } = await params
  const dictionary = await getDictionary(lang)

  const {
    lang: langFromDictionary,
    header: { stringConnector },
  } = dictionary

  return (
    <html
      lang={langFromDictionary}
      className={`${geist.className} antialiased`}
    >
      <body className="flex flex-col items-center justify-center w-full h-svh">
        <Header
          stringConnector={stringConnector}
          defaultLanguage={langFromDictionary}
        />
        {children}
      </body>
    </html>
  )
}
