// Packages
import type { Metadata } from "next"
import { Geist, Inter, Open_Sans, Poppins } from "next/font/google"
// Dictionaries
import { DEFAULT_LANGUAGE, Locale } from "@/dictionaries/dictionaries"
// Context
import { DEFAULT_ACCENT_THEME, DEFAULT_FONT_THEME, ThemeProvider } from "@/context/ThemeContext"
// Types
import { FontTheme } from "@/types/shared"
// Next
import { cookies } from "next/headers"
// Styles
import "../globals.css"

interface RootLayoutProps {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const geist = Geist({
  subsets: ["latin"],
})
const openSans = Open_Sans({
  subsets: ["latin"],
})
const inter = Inter({
  subsets: ["latin"],
})
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] })

const FONTS_CLASSNAMES: Record<FontTheme, string> = {
  geist: geist.className,
  "open-sans": openSans.className,
  inter: inter.className,
  poppins: poppins.className,
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lang = DEFAULT_LANGUAGE } = await params

  // Fetch organization theme from internal API Route
  let accentColor = DEFAULT_ACCENT_THEME
  let font = DEFAULT_FONT_THEME

  try {
    const baseUrl = process.env.NEXT_PUBLIC_API_URL?.includes('localhost')
      ? 'http://localhost:3000'
      : (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000')
    
    const response = await fetch(`${baseUrl}/api/organization/theme`, {
      headers: {
        'Cookie': (await cookies()).toString(),
      },
      cache: 'no-store',
    })

    if (response.ok) {
      const result = await response.json()
      if (result.success && result.data) {
        accentColor = result.data.accentColor || DEFAULT_ACCENT_THEME
        font = result.data.font || DEFAULT_FONT_THEME
      }
    }
  } catch {
    // Use defaults on error
  }

  const fontClassName = FONTS_CLASSNAMES[font]

  return (
    <html
      lang={lang}
      className={`${fontClassName} antialiased`}
      data-accent-theme={accentColor}
      data-font-theme={font}
    >
      <body className="flex flex-col items-center justify-start w-full lg:h-svh bg-background">
        <ThemeProvider
          initialTheme={accentColor}
          initialFont={font}
          fontClassNames={FONTS_CLASSNAMES}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
